language: node_js

os:
  - "linux"
  - "osx"

node_js:
- '4'
- '5'
- '6'
- '7'
- 'node'

sudo: required
dist: xenial

before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then sudo apt-get install -qq imagemagick; fi"
  - "if [ ${TRAVIS_OS_NAME:-'osx'} = 'linux' ]; then sudo port install ImageMagick; fi"
